name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_NAME }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/spa_node/spa_node1
            sudo git pull origin master
            npm install
            sudo pm2 restart 0
